package goodroad.tasks;

import goodroad.api.ApiErrors.ApiException;
import goodroad.obstacle.repository.*;
import goodroad.points.PointLedgerService;
import goodroad.security.Crypto;
import goodroad.tasks.repository.*;
import goodroad.users.repository.*;
import goodroad.validation.GeoUtils;
import goodroad.volunteer.repository.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class TaskService {
    private static final double RADIUS_KM = 5.0;
    private static final Duration HELP_REQUEST_MIN_AGE = Duration.ofHours(24);
    private static final int MAX_REVIEW_COUNT_FOR_TASK = 50;
    private static final Duration GENERATION_COOLDOWN = Duration.ofMinutes(15);
    private static final double GENERATION_MOVE_THRESHOLD_KM = 1.0;

    private final UserRepo users;
    private final TaskRepo tasks;
    private final TaskTargetRepo targets;
    private final UserTaskTargetCompletionRepo targetCompletions;
    private final UserTaskCompletionRepo taskCompletions;
    private final ObstacleFeatureRepo features;
    private final HelpRequestRepo helpRequests;
    private final PointLedgerService ledger;
    private final TaskGenerationStateRepo generationStates;

    public TaskService(UserRepo users, TaskRepo tasks, TaskTargetRepo targets,
                       UserTaskTargetCompletionRepo targetCompletions, UserTaskCompletionRepo taskCompletions,
                       ObstacleFeatureRepo features, HelpRequestRepo helpRequests, PointLedgerService ledger,
                       TaskGenerationStateRepo generationStates) {
        this.users = users;
        this.tasks = tasks;
        this.targets = targets;
        this.targetCompletions = targetCompletions;
        this.taskCompletions = taskCompletions;
        this.features = features;
        this.helpRequests = helpRequests;
        this.ledger = ledger;
        this.generationStates = generationStates;
    }

    public record TargetView(String id, String targetType, String targetId, String title, Double latitude, Double longitude, boolean done) {}
    public record TaskView(String id, String activityType, String title, int points, int targetCount, int completedCount, boolean autoGenerated, List<TargetView> targets) {}
    public record CompletedTaskView(String id, String taskId, String taskTitle, int pointsAwarded, java.time.Instant createdAt) {}
    public record GenerationReq(Double latitude, Double longitude) {}
    public record GenerationResult(int createdTasks, boolean skipped, String reason, Instant generatedAt) {}

    @Transactional(readOnly = true)
    public List<TaskView> feed(String phoneFromAuth, String activityType, Double latitude, Double longitude) {
        UserEntity user = findCurrent(phoneFromAuth, false);
        if ((latitude == null) != (longitude == null)) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "TASK_LOCATION_INCOMPLETE", "Для фильтрации укажите и широту, и долготу");
        }
        if (latitude != null) {
            GeoUtils.requireCoordinates(latitude, longitude, "TASK_LOCATION_INVALID");
        }
        String type = requireValidActivityFilter(activityType);
        List<TaskEntity> raw = type == null
                ? tasks.findByStatusOrderByCreatedAtDesc("ACTIVE")
                : tasks.findByActivityTypeAndStatusOrderByCreatedAtDesc(type, "ACTIVE");
        raw = raw.stream()
                .filter(task -> task.getAssignedUserId() == null || task.getAssignedUserId().equals(user.getId()))
                .filter(task -> !taskCompletions.existsByUserIdAndTaskId(user.getId(), task.getId()))
                .filter(task -> isNear(task.getCenterLatitude(), task.getCenterLongitude(), latitude, longitude))
                .toList();
        return buildViews(user, raw);
    }

    @Transactional(readOnly = true)
    public List<CompletedTaskView> completed(String phoneFromAuth) {
        UserEntity user = findCurrent(phoneFromAuth, false);
        return taskCompletions.findByUserIdOrderByCreatedAtDesc(user.getId()).stream()
                .map(c -> {
                    TaskEntity task = tasks.findById(c.getTaskId()).orElse(null);
                    String taskTitle = task != null ? task.getTitle() : "Задание";
                    return new CompletedTaskView(c.getId() == null ? null : c.getId().toString(), c.getTaskId().toString(), taskTitle, c.getPointsAwarded(), c.getCreatedAt());
                })
                .toList();
    }

    @Transactional
    public GenerationResult generateForCurrentLocation(String phoneFromAuth, GenerationReq request) {
        if (request == null) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "TASK_GENERATION_BODY_EMPTY", "Укажите текущее местоположение");
        }
        GeoUtils.Coordinates location = GeoUtils.requireCoordinates(request.latitude(), request.longitude(), "TASK_LOCATION_INVALID");
        UserEntity user = findCurrent(phoneFromAuth, true);
        Instant now = Instant.now();
        TaskGenerationStateEntity previous = generationStates.findById(user.getId()).orElse(null);
        if (previous != null
                && previous.getGeneratedAt() != null
                && previous.getGeneratedAt().plus(GENERATION_COOLDOWN).isAfter(now)
                && GeoUtils.distanceKm(previous.getLatitude(), previous.getLongitude(), location.latitude(), location.longitude()) < GENERATION_MOVE_THRESHOLD_KM) {
            return new GenerationResult(0, true, "LOCATION_UNCHANGED", previous.getGeneratedAt());
        }

        int before = tasks.findByStatusAndAssignedUserIdOrderByCreatedAtDesc("ACTIVE", user.getId()).size();
        expireOpenHelpRequests();
        generateReviewTasks(user, location.latitude(), location.longitude());
        if ("VOLUNTEER".equals(user.getRole())) {
            refreshVolunteerTasks(user, location.latitude(), location.longitude());
        }
        int after = tasks.findByStatusAndAssignedUserIdOrderByCreatedAtDesc("ACTIVE", user.getId()).size();

        TaskGenerationStateEntity state = previous == null ? new TaskGenerationStateEntity() : previous;
        state.setUserId(user.getId());
        state.setLatitude(location.latitude());
        state.setLongitude(location.longitude());
        state.setGeneratedAt(now);
        generationStates.save(state);
        return new GenerationResult(Math.max(0, after - before), false, null, now);
    }

    @Transactional
    public void registerApprovedReview(Long userId, Long featureId, Long reviewId) {
        registerTargetCompletion(userId, "OBSTACLE_FEATURE", featureId, "REVIEW", reviewId);
    }

    @Transactional
    public void registerCompletedHelp(Long volunteerId, Long helpRequestId) {
        registerTargetCompletion(volunteerId, "HELP_REQUEST", helpRequestId, "HELP_REQUEST", helpRequestId);
    }

    private void registerTargetCompletion(Long userId, String targetType, Long targetObjectId, String sourceType, Long sourceId) {
        if (userId == null || targetObjectId == null) return;
        UserEntity user = users.findByIdForUpdate(userId).orElse(null);
        if (user == null) return;
        for (TaskTargetEntity target : targets.findByTargetTypeAndTargetId(targetType, targetObjectId)) {
            TaskEntity task = tasks.findById(target.getTaskId()).orElse(null);
            if (task == null || !"ACTIVE".equals(task.getStatus())) continue;
            if (task.getAssignedUserId() != null && !task.getAssignedUserId().equals(userId)) continue;
            if (taskCompletions.existsByUserIdAndTaskId(userId, target.getTaskId()) || targetCompletions.existsByUserIdAndTargetId(userId, target.getId())) continue;
            target.setStatus("ACTIVE");
            targets.save(target);
            UserTaskTargetCompletionEntity done = new UserTaskTargetCompletionEntity();
            done.setUserId(userId);
            done.setTaskId(target.getTaskId());
            done.setTargetId(target.getId());
            done.setSourceType(sourceType);
            done.setSourceId(sourceId);
            targetCompletions.save(done);
            if (targetCompletions.countByUserIdAndTaskId(userId, task.getId()) >= task.getTargetCount()) {
                completeTask(user, task, sourceType, sourceId);
            }
        }
    }

    private void completeTask(UserEntity user, TaskEntity task, String sourceType, Long sourceId) {
        if (taskCompletions.existsByUserIdAndTaskId(user.getId(), task.getId())) return;
        UserTaskCompletionEntity completion = new UserTaskCompletionEntity();
        completion.setUserId(user.getId());
        completion.setTaskId(task.getId());
        completion.setPointsAwarded(task.getPoints());
        taskCompletions.save(completion);
        user.setCompletedTasksCount(safe(user.getCompletedTasksCount()) == Integer.MAX_VALUE
                ? Integer.MAX_VALUE
                : safe(user.getCompletedTasksCount()) + 1);
        ledger.earn(user, task.getPoints(), "TASK_COMPLETED", task.getTitle(), task.getId(), sourceType, sourceId);
        if (task.getAssignedUserId() != null) {
            task.setStatus("ARCHIVED");
            tasks.save(task);
        }
    }

    private List<TaskView> buildViews(UserEntity user, List<TaskEntity> rawTasks) {
        if (rawTasks.isEmpty()) return List.of();
        List<Long> taskIds = rawTasks.stream().map(TaskEntity::getId).toList();
        Map<Long, List<TaskTargetEntity>> byTask = targets.findByTaskIdInOrderBySortOrderAscIdAsc(taskIds).stream()
                .filter(target -> target.getStatus() == null || !"UNAVAILABLE".equals(target.getStatus()))
                .collect(Collectors.groupingBy(TaskTargetEntity::getTaskId, LinkedHashMap::new, Collectors.toList()));
        Set<Long> doneTargetIds = user == null ? Set.of() : targetCompletions.findByUserIdAndTaskIdIn(user.getId(), taskIds).stream()
                                                            .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
        return rawTasks.stream().map(task -> {
            List<TargetView> targetViews = byTask.getOrDefault(task.getId(), List.of()).stream()
                    .map(target -> new TargetView(target.getId().toString(), target.getTargetType(), target.getTargetId().toString(), target.getTitle(), target.getLatitude(), target.getLongitude(), doneTargetIds.contains(target.getId())))
                    .toList();
            int completedCount = (int) targetViews.stream().filter(TargetView::done).count();
            return new TaskView(task.getId().toString(), task.getActivityType(), task.getTitle(), task.getPoints(), task.getTargetCount(), completedCount, task.isAutoGenerated(), targetViews);
        }).toList();
    }

    private void generateReviewTasks(UserEntity user, double latitude, double longitude) {
        refreshReviewTasks(user, latitude, longitude);
        for (int count : List.of(3, 5, 10)) {
            boolean hasActive = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("REVIEW", "ACTIVE", user.getId()).stream()
                    .anyMatch(task -> Objects.equals(task.getTargetCount(), count));
            if (hasActive) continue;
            List<ObstacleFeatureEntity> picked = findReplacementReviewFeatures(user.getId(), latitude, longitude, Set.of(), count);
            if (picked.size() < count) continue;
            TaskEntity task = new TaskEntity();
            task.setActivityType("REVIEW");
            task.setTitle("Оцените " + count + " мало проверенных точек рядом с вами");
            task.setTargetCount(count);
            task.setPoints(defaultPoints("REVIEW", count));
            task.setAutoGenerated(true);
            task.setCenterLatitude(latitude);
            task.setCenterLongitude(longitude);
            task.setAssignedUserId(user.getId());
            tasks.save(task);
            int order = 0;
            for (ObstacleFeatureEntity feature : picked) {
                addTarget(task, "OBSTACLE_FEATURE", feature.getId(), address(feature), feature.getLat(), feature.getLon(), order++);
            }
        }
    }

    private void refreshReviewTasks(UserEntity user, double latitude, double longitude) {
        List<TaskEntity> reviewTasks = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("REVIEW", "ACTIVE", user.getId());
        for (TaskEntity task : reviewTasks) {
            List<TaskTargetEntity> taskTargets = targets.findByTaskIdOrderBySortOrderAscIdAsc(task.getId());
            Set<Long> doneTargetIds = targetCompletions.findByUserIdAndTaskIdIn(user.getId(), List.of(task.getId())).stream()
                    .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
            Set<Long> usedFeatureIds = new HashSet<>();
            int maxOrder = taskTargets.stream().map(TaskTargetEntity::getSortOrder).filter(Objects::nonNull).max(Integer::compareTo).orElse(-1);
            for (TaskTargetEntity target : taskTargets) {
                if (!"OBSTACLE_FEATURE".equals(target.getTargetType())) continue;
                usedFeatureIds.add(target.getTargetId());
                if (doneTargetIds.contains(target.getId())) {
                    continue;
                }
                ObstacleFeatureEntity feature = features.findById(target.getTargetId()).orElse(null);
                boolean valid = feature != null
                        && safe(feature.getReviewsCount()) <= MAX_REVIEW_COUNT_FOR_TASK
                        && Double.isFinite(feature.getLat())
                        && Double.isFinite(feature.getLon())
                        && GeoUtils.distanceKm(latitude, longitude, feature.getLat(), feature.getLon()) <= RADIUS_KM;
                if (valid) {
                    usedFeatureIds.add(target.getTargetId());
                    target.setStatus("ACTIVE");
                    continue;
                }
                target.setStatus("UNAVAILABLE");
                targets.save(target);
            }
            long visibleOrDone = taskTargets.stream()
                    .filter(target -> doneTargetIds.contains(target.getId()) || !"UNAVAILABLE".equals(target.getStatus()))
                    .count();
            int missing = task.getTargetCount() - (int) visibleOrDone;
            if (missing > 0) {
                List<ObstacleFeatureEntity> replacements = findReplacementReviewFeatures(user.getId(), latitude, longitude, usedFeatureIds, missing);
                for (ObstacleFeatureEntity feature : replacements) {
                    addTarget(task, "OBSTACLE_FEATURE", feature.getId(), address(feature), feature.getLat(), feature.getLon(), ++maxOrder);
                    usedFeatureIds.add(feature.getId());
                }
            }
        }
    }

    private List<ObstacleFeatureEntity> findReplacementReviewFeatures(Long userId, double latitude, double longitude, Set<Long> excludedFeatureIds, int count) {
        Set<Long> excluded = new HashSet<>(excludedFeatureIds);
        excluded.addAll(activePersonalTargetIds(userId, "REVIEW", "OBSTACLE_FEATURE"));
        List<ObstacleFeatureEntity> result = new ArrayList<>();
        for (ObstacleFeatureEntity feature : features.findLowReviewedByBbox(latitude - 0.06, latitude + 0.06, longitude - 0.1, longitude + 0.1, MAX_REVIEW_COUNT_FOR_TASK)) {
            if (feature.getId() == null || excluded.contains(feature.getId())) continue;
            if (!Double.isFinite(feature.getLat()) || !Double.isFinite(feature.getLon())) continue;
            if (GeoUtils.distanceKm(latitude, longitude, feature.getLat(), feature.getLon()) > RADIUS_KM) continue;
            result.add(feature);
            excluded.add(feature.getId());
            if (result.size() == count) break;
        }
        return result;
    }

    private void refreshVolunteerTasks(UserEntity user, double latitude, double longitude) {
        refreshExistingVolunteerTasks(user, latitude, longitude);
        for (int count : List.of(1, 3)) {
            boolean hasActive = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("VOLUNTEER", "ACTIVE", user.getId()).stream()
                    .anyMatch(task -> Objects.equals(task.getTargetCount(), count));
            if (hasActive) continue;
            List<HelpRequestEntity> picked = findReplacementHelpRequests(user.getId(), latitude, longitude, Set.of(), Set.of(), count);
            if (picked.size() < count) continue;
            TaskEntity task = new TaskEntity();
            task.setActivityType("VOLUNTEER");
            task.setTitle(volunteerTaskTitle(count));
            task.setTargetCount(count);
            task.setPoints(defaultPoints("VOLUNTEER", count));
            task.setAutoGenerated(true);
            task.setCenterLatitude(latitude);
            task.setCenterLongitude(longitude);
            task.setAssignedUserId(user.getId());
            tasks.save(task);
            int order = 0;
            for (HelpRequestEntity request : picked) {
                addTarget(task, "HELP_REQUEST", request.getId(), helpRequestTitle(request), request.getStartLatitude(), request.getStartLongitude(), order++);
            }
        }
    }

    private void refreshExistingVolunteerTasks(UserEntity user, double latitude, double longitude) {
        List<TaskEntity> volunteerTasks = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("VOLUNTEER", "ACTIVE", user.getId());
        for (TaskEntity task : volunteerTasks) {
            if (task.getTargetCount() == null || (task.getTargetCount() != 1 && task.getTargetCount() != 3)) {
                task.setStatus("ARCHIVED");
                tasks.save(task);
                continue;
            }
            List<TaskTargetEntity> taskTargets = targets.findByTaskIdOrderBySortOrderAscIdAsc(task.getId());
            Set<Long> doneTargetIds = targetCompletions.findByUserIdAndTaskIdIn(user.getId(), List.of(task.getId())).stream()
                    .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
            Set<Long> usedRequestIds = new HashSet<>();
            Set<LocalDateTime> usedStarts = new HashSet<>();
            int maxOrder = taskTargets.stream().map(TaskTargetEntity::getSortOrder).filter(Objects::nonNull).max(Integer::compareTo).orElse(-1);
            for (TaskTargetEntity target : taskTargets) {
                if (!"HELP_REQUEST".equals(target.getTargetType())) continue;
                usedRequestIds.add(target.getTargetId());
                HelpRequestEntity request = helpRequests.findById(target.getTargetId()).orElse(null);
                if (request != null && doneTargetIds.contains(target.getId())) {
                    usedStarts.add(startOf(request));
                    continue;
                }
                boolean valid = isHelpRequestValidForVolunteer(request, user.getId(), latitude, longitude);
                if (valid) {
                    target.setStatus("ACTIVE");
                    usedStarts.add(startOf(request));
                    continue;
                }
                target.setStatus("UNAVAILABLE");
                targets.save(target);
            }
            long visibleOrDone = taskTargets.stream()
                    .filter(target -> doneTargetIds.contains(target.getId()) || !"UNAVAILABLE".equals(target.getStatus()))
                    .count();
            int missing = task.getTargetCount() - (int) visibleOrDone;
            if (missing > 0) {
                List<HelpRequestEntity> replacements = findReplacementHelpRequests(user.getId(), latitude, longitude, usedRequestIds, usedStarts, missing);
                for (HelpRequestEntity request : replacements) {
                    addTarget(task, "HELP_REQUEST", request.getId(), helpRequestTitle(request), request.getStartLatitude(), request.getStartLongitude(), ++maxOrder);
                    usedRequestIds.add(request.getId());
                    usedStarts.add(startOf(request));
                }
            }
        }
    }

    private boolean isHelpRequestValidForVolunteer(HelpRequestEntity request, Long volunteerId, double latitude, double longitude) {
        if (request == null) return false;
        if (request.getStartLatitude() == null || request.getStartLongitude() == null) return false;
        if (GeoUtils.distanceKm(latitude, longitude, request.getStartLatitude(), request.getStartLongitude()) > RADIUS_KM) return false;
        if ("OPEN".equals(request.getStatus())) return !request.getRequester().getId().equals(volunteerId) && isOldEnough(request) && !isPast(request);
        boolean assignedToThisVolunteer = request.getVolunteer() != null && request.getVolunteer().getId().equals(volunteerId);
        return assignedToThisVolunteer && ("ACCEPTED".equals(request.getStatus()) || "COMPLETED".equals(request.getStatus()));
    }

    private List<HelpRequestEntity> findReplacementHelpRequests(Long volunteerId, double latitude, double longitude, Set<Long> excludedRequestIds, Set<LocalDateTime> usedStarts, int count) {
        Set<Long> excluded = new HashSet<>(excludedRequestIds);
        excluded.addAll(activePersonalTargetIds(volunteerId, "VOLUNTEER", "HELP_REQUEST"));
        Set<LocalDateTime> starts = new HashSet<>(usedStarts);
        List<HelpRequestEntity> result = new ArrayList<>();
        for (HelpRequestEntity request : helpRequests.findByStatusOrderByDateAscTimeAscCreatedAtAsc("OPEN")) {
            if (request.getId() == null || excluded.contains(request.getId())) continue;
            if (request.getRequester().getId().equals(volunteerId)) continue;
            if (request.getStartLatitude() == null || request.getStartLongitude() == null) continue;
            if (!isOldEnough(request) || isPast(request)) continue;
            if (GeoUtils.distanceKm(latitude, longitude, request.getStartLatitude(), request.getStartLongitude()) > RADIUS_KM) continue;
            LocalDateTime start = startOf(request);
            if (!starts.add(start)) continue;
            result.add(request);
            excluded.add(request.getId());
            if (result.size() == count) break;
        }
        return result;
    }

    private Set<Long> activePersonalTargetIds(Long userId, String activityType, String targetType) {
        List<TaskEntity> active = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc(activityType, "ACTIVE", userId);
        if (active.isEmpty()) return Set.of();
        return targets.findByTaskIdInOrderBySortOrderAscIdAsc(active.stream().map(TaskEntity::getId).toList()).stream()
                .filter(target -> targetType.equals(target.getTargetType()))
                .filter(target -> target.getStatus() == null || !"UNAVAILABLE".equals(target.getStatus()))
                .map(TaskTargetEntity::getTargetId)
                .collect(Collectors.toSet());
    }

    private TaskTargetEntity addTarget(TaskEntity task, String targetType, Long targetId, String title, Double latitude, Double longitude, int order) {
        TaskTargetEntity target = new TaskTargetEntity();
        target.setTaskId(task.getId());
        target.setTargetType(targetType);
        target.setTargetId(targetId);
        target.setTitle(title);
        target.setLatitude(latitude);
        target.setLongitude(longitude);
        target.setSortOrder(order);
        target.setStatus("ACTIVE");
        return targets.save(target);
    }

    private boolean isOldEnough(HelpRequestEntity request) {
        return request.getCreatedAt() != null && request.getCreatedAt().plus(HELP_REQUEST_MIN_AGE).isBefore(Instant.now());
    }

    private boolean isPast(HelpRequestEntity request) {
        return LocalDateTime.of(request.getDate(), request.getTime()).isBefore(LocalDateTime.now());
    }

    private LocalDateTime startOf(HelpRequestEntity request) {
        return LocalDateTime.of(request.getDate(), request.getTime());
    }

    private String volunteerTaskTitle(int count) {
        return count == 1 ? "Помогите одному человеку с прогулкой рядом с вами" : "Помогите трем людям с прогулкой рядом с вами";
    }

    private String helpRequestTitle(HelpRequestEntity request) {
        return request.getFromAddress() + " → " + request.getToAddress() + ", " + request.getDate() + " " + request.getTime();
    }

    private String address(ObstacleFeatureEntity f) {
        String place = trim(f.getPlaceName());
        String base = String.join(", ", java.util.stream.Stream.of(f.getCity(), f.getStreet(), f.getHouse()).filter(Objects::nonNull).filter(s -> !s.isBlank()).toList());
        return place == null ? base : place + ", " + base;
    }

    private boolean isNear(Double centerLat, Double centerLon, Double lat, Double lon) {
        if (lat == null || lon == null || centerLat == null || centerLon == null) return true;
        return GeoUtils.distanceKm(lat, lon, centerLat, centerLon) <= RADIUS_KM;
    }

    private int defaultPoints(String type, int count) {
        if ("VOLUNTEER".equals(type)) return count == 1 ? 50 : 120;
        return count == 3 ? 30 : count == 5 ? 50 : 100;
    }

    private String normalizeActivity(String raw) {
        String v = trim(raw);
        if (v == null) return null;
        v = v.toUpperCase(Locale.ROOT);
        if (v.equals("REVIEWS")) v = "REVIEW";
        if (v.equals("VOLUNTEERING")) v = "VOLUNTEER";
        return (v.equals("REVIEW") || v.equals("VOLUNTEER")) ? v : null;
    }

    private String requireValidActivityFilter(String raw) {
        String normalized = normalizeActivity(raw);
        if (trim(raw) != null && normalized == null) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "TASK_ACTIVITY_INVALID", "Тип активности должен быть REVIEW или VOLUNTEER");
        }
        return normalized;
    }

    private void expireOpenHelpRequests() {
        LocalDate today = LocalDate.now();
        LocalTime now = LocalTime.now();
        List<HelpRequestEntity> expired = new ArrayList<>();
        expired.addAll(helpRequests.findByStatusAndDateBefore("OPEN", today));
        expired.addAll(helpRequests.findByStatusAndDateAndTimeBefore("OPEN", today, now));
        if (expired.isEmpty()) return;
        Instant cancelledAt = Instant.now();
        for (HelpRequestEntity request : expired) {
            request.setStatus("CANCELLED");
            request.setCancelledAt(cancelledAt);
        }
        helpRequests.saveAll(expired);
    }

    private UserEntity findCurrent(String phoneFromAuth, boolean forUpdate) {
        String phoneNorm = Crypto.normPhone(phoneFromAuth);
        if (phoneNorm.isEmpty()) {
            throw new ApiException(HttpStatus.UNAUTHORIZED, "USER_PHONE_NOT_FOUND", "User with given phone not found");
        }
        String phoneHash = Crypto.sha256Hex(phoneNorm);
        Optional<UserEntity> result = forUpdate
                ? users.findByPhoneHashForUpdate(phoneHash)
                : users.findByPhoneHash(phoneHash);
        return result.filter(UserEntity::isActive)
                .orElseThrow(() -> new ApiException(HttpStatus.UNAUTHORIZED, "USER_PHONE_NOT_FOUND", "User with given phone not found"));
    }

    private static int safe(Integer value) {
        return value == null ? 0 : Math.max(0, value);
    }

    private static String trim(String s) { return s == null || s.isBlank() ? null : s.trim(); }
}