package goodroad.tasks;

import goodroad.api.ApiErrors.ApiException;
import goodroad.obstacle.repository.*;
import goodroad.points.PointLedgerService;
import goodroad.security.Crypto;
import goodroad.tasks.repository.*;
import goodroad.users.repository.*;
import goodroad.volunteer.repository.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class TaskService {
    private static final double RADIUS_KM = 5.0;
    private static final Duration HELP_REQUEST_MIN_AGE = Duration.ofHours(24);
    private static final int MAX_REVIEW_COUNT_FOR_TASK = 50;

    private final UserRepo users;
    private final TaskRepo tasks;
    private final TaskTargetRepo targets;
    private final UserTaskTargetCompletionRepo targetCompletions;
    private final UserTaskCompletionRepo taskCompletions;
    private final ObstacleFeatureRepo features;
    private final HelpRequestRepo helpRequests;
    private final PointLedgerService ledger;

    public TaskService(UserRepo users, TaskRepo tasks, TaskTargetRepo targets,
                       UserTaskTargetCompletionRepo targetCompletions, UserTaskCompletionRepo taskCompletions,
                       ObstacleFeatureRepo features, HelpRequestRepo helpRequests, PointLedgerService ledger) {
        this.users = users;
        this.tasks = tasks;
        this.targets = targets;
        this.targetCompletions = targetCompletions;
        this.taskCompletions = taskCompletions;
        this.features = features;
        this.helpRequests = helpRequests;
        this.ledger = ledger;
    }

    public record TargetView(String id, String targetType, String targetId, String title, Double latitude, Double longitude, boolean done) {}
    public record TaskView(String id, String activityType, String title, int points, int targetCount, int completedCount, boolean autoGenerated, List<TargetView> targets) {}
    public record CompletedTaskView(String id, String taskId, String taskTitle, int pointsAwarded, java.time.Instant createdAt) {}
    public record TaskCreateReq(String activityType, String title, int targetCount, Integer points, Double latitude, Double longitude, List<TaskTargetCreateReq> targets) {}
    public record TaskTargetCreateReq(String targetType, Long targetId, String title, Double latitude, Double longitude) {}

    @Transactional
    public List<TaskView> feed(String phoneFromAuth, String activityType, Double latitude, Double longitude) {
        UserEntity user = findCurrent(phoneFromAuth);
        expireOpenHelpRequests();
        if (latitude != null && longitude != null) {
            generateReviewTasks(user, latitude, longitude);
            if ("VOLUNTEER".equals(normalizeActivity(activityType))) {
                refreshVolunteerTasks(user, latitude, longitude);
            }
        }
        String type = normalizeActivity(activityType);
        List<TaskEntity> raw = type == null
                ? tasks.findByStatusOrderByCreatedAtDesc("ACTIVE")
                : tasks.findByActivityTypeAndStatusOrderByCreatedAtDesc(type, "ACTIVE");
        raw = raw.stream()
                .filter(task -> task.getAssignedUserId() == null || task.getAssignedUserId().equals(user.getId()))
                .filter(task -> !taskCompletions.existsByUserIdAndTaskId(user.getId(), task.getId()))
                .filter(task -> isNear(task.getCenterLatitude(), task.getCenterLongitude(), latitude, longitude))
                .toList();
        return buildViews(user, raw);
    }

    @Transactional(readOnly = true)
    public List<CompletedTaskView> completed(String phoneFromAuth) {
        UserEntity user = findCurrent(phoneFromAuth);
        return taskCompletions.findByUserIdOrderByCreatedAtDesc(user.getId()).stream()
                .map(c -> {
                    TaskEntity task = tasks.findById(c.getTaskId()).orElse(null);
                    String taskTitle = task != null ? task.getTitle() : "Задание";
                    return new CompletedTaskView(c.getId() == null ? null : c.getId().toString(), c.getTaskId().toString(), taskTitle, c.getPointsAwarded(), c.getCreatedAt());
                })
                .toList();
    }

    @Transactional
    public TaskView createTask(TaskCreateReq req) {
        if (req == null) throw bad("TASK_EMPTY", "Task is empty");
        String type = normalizeActivity(req.activityType());
        if (type == null) throw bad("TASK_ACTIVITY_INVALID", "Task activity type is invalid");
        int targetCount = req.targetCount();
        if (!isAllowedTargetCount(type, targetCount)) throw bad("TASK_TARGET_COUNT_INVALID", "Task target count is invalid");
        int points = req.points() == null ? defaultPoints(type, targetCount) : req.points();
        if (points <= 0) throw bad("TASK_POINTS_INVALID", "Task points are invalid");
        String title = trim(req.title());
        if (title == null) throw bad("TASK_TITLE_EMPTY", "Task title is empty");
        if (req.targets() == null || req.targets().size() < targetCount) throw bad("TASK_TARGETS_NOT_ENOUGH", "Task targets are not enough");
        TaskEntity task = new TaskEntity();
        task.setActivityType(type);
        task.setTitle(title);
        task.setTargetCount(targetCount);
        task.setPoints(points);
        task.setCenterLatitude(req.latitude());
        task.setCenterLongitude(req.longitude());
        tasks.save(task);
        int order = 0;
        for (TaskTargetCreateReq targetReq : req.targets().stream().limit(targetCount).toList()) {
            addTarget(task, requireTargetType(targetReq.targetType(), type), Objects.requireNonNull(targetReq.targetId(), "targetId"), Optional.ofNullable(trim(targetReq.title())).orElse("Цель задания #" + targetReq.targetId()), targetReq.latitude(), targetReq.longitude(), order++);
        }
        return buildViews(null, List.of(task)).get(0);
    }

    @Transactional
    public void registerApprovedReview(Long userId, Long featureId, Long reviewId) {
        registerTargetCompletion(userId, "OBSTACLE_FEATURE", featureId, "REVIEW", reviewId);
    }

    @Transactional
    public void registerCompletedHelp(Long volunteerId, Long helpRequestId) {
        registerTargetCompletion(volunteerId, "HELP_REQUEST", helpRequestId, "HELP_REQUEST", helpRequestId);
    }

    private void registerTargetCompletion(Long userId, String targetType, Long targetObjectId, String sourceType, Long sourceId) {
        if (userId == null || targetObjectId == null) return;
        UserEntity user = users.findById(userId).orElse(null);
        if (user == null) return;
        for (TaskTargetEntity target : targets.findByTargetTypeAndTargetId(targetType, targetObjectId)) {
            TaskEntity task = tasks.findById(target.getTaskId()).orElse(null);
            if (task == null || !"ACTIVE".equals(task.getStatus())) continue;
            if (task.getAssignedUserId() != null && !task.getAssignedUserId().equals(userId)) continue;
            if (taskCompletions.existsByUserIdAndTaskId(userId, target.getTaskId()) || targetCompletions.existsByUserIdAndTargetId(userId, target.getId())) continue;
            target.setStatus("ACTIVE");
            targets.save(target);
            UserTaskTargetCompletionEntity done = new UserTaskTargetCompletionEntity();
            done.setUserId(userId);
            done.setTaskId(target.getTaskId());
            done.setTargetId(target.getId());
            done.setSourceType(sourceType);
            done.setSourceId(sourceId);
            targetCompletions.save(done);
            if (targetCompletions.countByUserIdAndTaskId(userId, task.getId()) >= task.getTargetCount()) {
                completeTask(user, task, sourceType, sourceId);
            }
        }
    }

    private void completeTask(UserEntity user, TaskEntity task, String sourceType, Long sourceId) {
        if (taskCompletions.existsByUserIdAndTaskId(user.getId(), task.getId())) return;
        UserTaskCompletionEntity completion = new UserTaskCompletionEntity();
        completion.setUserId(user.getId());
        completion.setTaskId(task.getId());
        completion.setPointsAwarded(task.getPoints());
        taskCompletions.save(completion);
        user.setCompletedTasksCount(safe(user.getCompletedTasksCount()) + 1);
        ledger.earn(user, task.getPoints(), "TASK_COMPLETED", task.getTitle(), task.getId(), sourceType, sourceId);
    }

    private List<TaskView> buildViews(UserEntity user, List<TaskEntity> rawTasks) {
        if (rawTasks.isEmpty()) return List.of();
        List<Long> taskIds = rawTasks.stream().map(TaskEntity::getId).toList();
        Map<Long, List<TaskTargetEntity>> byTask = targets.findByTaskIdInOrderBySortOrderAscIdAsc(taskIds).stream()
                .filter(target -> target.getStatus() == null || !"UNAVAILABLE".equals(target.getStatus()))
                .collect(Collectors.groupingBy(TaskTargetEntity::getTaskId, LinkedHashMap::new, Collectors.toList()));
        Set<Long> doneTargetIds = user == null ? Set.of() : targetCompletions.findByUserIdAndTaskIdIn(user.getId(), taskIds).stream()
                                                            .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
        return rawTasks.stream().map(task -> {
            List<TargetView> targetViews = byTask.getOrDefault(task.getId(), List.of()).stream()
                    .map(target -> new TargetView(target.getId().toString(), target.getTargetType(), target.getTargetId().toString(), target.getTitle(), target.getLatitude(), target.getLongitude(), doneTargetIds.contains(target.getId())))
                    .toList();
            int completedCount = (int) targetViews.stream().filter(TargetView::done).count();
            return new TaskView(task.getId().toString(), task.getActivityType(), task.getTitle(), task.getPoints(), task.getTargetCount(), completedCount, task.isAutoGenerated(), targetViews);
        }).toList();
    }

    private void generateReviewTasks(UserEntity user, double latitude, double longitude) {
        refreshReviewTasks(user, latitude, longitude);
        for (int count : List.of(3, 5, 10)) {
            boolean hasActive = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("REVIEW", "ACTIVE", user.getId()).stream()
                    .anyMatch(task -> Objects.equals(task.getTargetCount(), count));
            if (hasActive) continue;
            List<ObstacleFeatureEntity> picked = findReplacementReviewFeatures(user.getId(), latitude, longitude, Set.of(), count);
            if (picked.size() < count) continue;
            TaskEntity task = new TaskEntity();
            task.setActivityType("REVIEW");
            task.setTitle("Оцените " + count + " мало проверенных точек рядом с вами");
            task.setTargetCount(count);
            task.setPoints(defaultPoints("REVIEW", count));
            task.setAutoGenerated(true);
            task.setCenterLatitude(latitude);
            task.setCenterLongitude(longitude);
            task.setAssignedUserId(user.getId());
            tasks.save(task);
            int order = 0;
            for (ObstacleFeatureEntity feature : picked) {
                addTarget(task, "OBSTACLE_FEATURE", feature.getId(), address(feature), feature.getLat(), feature.getLon(), order++);
            }
        }
    }

    private void refreshReviewTasks(UserEntity user, double latitude, double longitude) {
        List<TaskEntity> reviewTasks = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("REVIEW", "ACTIVE", user.getId());
        for (TaskEntity task : reviewTasks) {
            List<TaskTargetEntity> taskTargets = targets.findByTaskIdOrderBySortOrderAscIdAsc(task.getId());
            Set<Long> doneTargetIds = targetCompletions.findByUserIdAndTaskIdIn(user.getId(), List.of(task.getId())).stream()
                    .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
            Set<Long> usedFeatureIds = new HashSet<>();
            int maxOrder = taskTargets.stream().map(TaskTargetEntity::getSortOrder).filter(Objects::nonNull).max(Integer::compareTo).orElse(-1);
            for (TaskTargetEntity target : taskTargets) {
                if (!"OBSTACLE_FEATURE".equals(target.getTargetType())) continue;
                usedFeatureIds.add(target.getTargetId());
                if (doneTargetIds.contains(target.getId())) {
                    continue;
                }
                ObstacleFeatureEntity feature = features.findById(target.getTargetId()).orElse(null);
                boolean valid = feature != null
                        && safe(feature.getReviewsCount()) <= MAX_REVIEW_COUNT_FOR_TASK
                        && Double.isFinite(feature.getLat())
                        && Double.isFinite(feature.getLon())
                        && distanceKm(latitude, longitude, feature.getLat(), feature.getLon()) <= RADIUS_KM;
                if (valid) {
                    usedFeatureIds.add(target.getTargetId());
                    target.setStatus("ACTIVE");
                    continue;
                }
                target.setStatus("UNAVAILABLE");
                targets.save(target);
            }
            long visibleOrDone = taskTargets.stream()
                    .filter(target -> doneTargetIds.contains(target.getId()) || !"UNAVAILABLE".equals(target.getStatus()))
                    .count();
            int missing = task.getTargetCount() - (int) visibleOrDone;
            if (missing > 0) {
                List<ObstacleFeatureEntity> replacements = findReplacementReviewFeatures(user.getId(), latitude, longitude, usedFeatureIds, missing);
                for (ObstacleFeatureEntity feature : replacements) {
                    addTarget(task, "OBSTACLE_FEATURE", feature.getId(), address(feature), feature.getLat(), feature.getLon(), ++maxOrder);
                    usedFeatureIds.add(feature.getId());
                }
            }
        }
    }

    private List<ObstacleFeatureEntity> findReplacementReviewFeatures(Long userId, double latitude, double longitude, Set<Long> excludedFeatureIds, int count) {
        Set<Long> excluded = new HashSet<>(excludedFeatureIds);
        excluded.addAll(activePersonalTargetIds(userId, "REVIEW", "OBSTACLE_FEATURE"));
        List<ObstacleFeatureEntity> result = new ArrayList<>();
        for (ObstacleFeatureEntity feature : features.findLowReviewedByBbox(latitude - 0.06, latitude + 0.06, longitude - 0.1, longitude + 0.1, MAX_REVIEW_COUNT_FOR_TASK)) {
            if (feature.getId() == null || excluded.contains(feature.getId())) continue;
            if (!Double.isFinite(feature.getLat()) || !Double.isFinite(feature.getLon())) continue;
            if (distanceKm(latitude, longitude, feature.getLat(), feature.getLon()) > RADIUS_KM) continue;
            result.add(feature);
            excluded.add(feature.getId());
            if (result.size() == count) break;
        }
        return result;
    }

    private void expireOpenHelpRequests() {
        LocalDate today = LocalDate.now();
        LocalTime now = LocalTime.now();
        List<HelpRequestEntity> expired = new ArrayList<>();
        expired.addAll(helpRequests.findByStatusAndDateBefore("OPEN", today));
        expired.addAll(helpRequests.findByStatusAndDateAndTimeBefore("OPEN", today, now));
        if (expired.isEmpty()) return;
        Instant cancelledAt = Instant.now();
        for (HelpRequestEntity request : expired) {
            request.setStatus("CANCELLED");
            request.setCancelledAt(cancelledAt);
        }
        helpRequests.saveAll(expired);
    }

    private void refreshVolunteerTasks(UserEntity user, double latitude, double longitude) {
        refreshExistingVolunteerTasks(user, latitude, longitude);
        for (int count : List.of(1, 3)) {
            boolean hasActive = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("VOLUNTEER", "ACTIVE", user.getId()).stream()
                    .anyMatch(task -> Objects.equals(task.getTargetCount(), count));
            if (hasActive) continue;
            List<HelpRequestEntity> picked = findReplacementHelpRequests(user.getId(), latitude, longitude, Set.of(), Set.of(), count);
            if (picked.size() < count) continue;
            TaskEntity task = new TaskEntity();
            task.setActivityType("VOLUNTEER");
            task.setTitle(volunteerTaskTitle(count));
            task.setTargetCount(count);
            task.setPoints(defaultPoints("VOLUNTEER", count));
            task.setAutoGenerated(true);
            task.setCenterLatitude(latitude);
            task.setCenterLongitude(longitude);
            task.setAssignedUserId(user.getId());
            tasks.save(task);
            int order = 0;
            for (HelpRequestEntity request : picked) {
                addTarget(task, "HELP_REQUEST", request.getId(), helpRequestTitle(request), request.getStartLatitude(), request.getStartLongitude(), order++);
            }
        }
    }

    private void refreshExistingVolunteerTasks(UserEntity user, double latitude, double longitude) {
        List<TaskEntity> volunteerTasks = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc("VOLUNTEER", "ACTIVE", user.getId());
        for (TaskEntity task : volunteerTasks) {
            if (task.getTargetCount() == null || (task.getTargetCount() != 1 && task.getTargetCount() != 3)) {
                task.setStatus("ARCHIVED");
                tasks.save(task);
                continue;
            }
            List<TaskTargetEntity> taskTargets = targets.findByTaskIdOrderBySortOrderAscIdAsc(task.getId());
            Set<Long> doneTargetIds = targetCompletions.findByUserIdAndTaskIdIn(user.getId(), List.of(task.getId())).stream()
                    .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
            Set<Long> usedRequestIds = new HashSet<>();
            Set<LocalDateTime> usedStarts = new HashSet<>();
            int maxOrder = taskTargets.stream().map(TaskTargetEntity::getSortOrder).filter(Objects::nonNull).max(Integer::compareTo).orElse(-1);
            for (TaskTargetEntity target : taskTargets) {
                if (!"HELP_REQUEST".equals(target.getTargetType())) continue;
                usedRequestIds.add(target.getTargetId());
                HelpRequestEntity request = helpRequests.findById(target.getTargetId()).orElse(null);
                if (request != null && doneTargetIds.contains(target.getId())) {
                    usedStarts.add(startOf(request));
                    continue;
                }
                boolean valid = isHelpRequestValidForVolunteer(request, user.getId(), latitude, longitude);
                if (valid) {
                    target.setStatus("ACTIVE");
                    usedStarts.add(startOf(request));
                    continue;
                }
                target.setStatus("UNAVAILABLE");
                targets.save(target);
            }
            long visibleOrDone = taskTargets.stream()
                    .filter(target -> doneTargetIds.contains(target.getId()) || !"UNAVAILABLE".equals(target.getStatus()))
                    .count();
            int missing = task.getTargetCount() - (int) visibleOrDone;
            if (missing > 0) {
                List<HelpRequestEntity> replacements = findReplacementHelpRequests(user.getId(), latitude, longitude, usedRequestIds, usedStarts, missing);
                for (HelpRequestEntity request : replacements) {
                    addTarget(task, "HELP_REQUEST", request.getId(), helpRequestTitle(request), request.getStartLatitude(), request.getStartLongitude(), ++maxOrder);
                    usedRequestIds.add(request.getId());
                    usedStarts.add(startOf(request));
                }
            }
        }
    }

    private boolean isHelpRequestValidForVolunteer(HelpRequestEntity request, Long volunteerId, double latitude, double longitude) {
        if (request == null) return false;
        if (request.getStartLatitude() == null || request.getStartLongitude() == null) return false;
        if (distanceKm(latitude, longitude, request.getStartLatitude(), request.getStartLongitude()) > RADIUS_KM) return false;
        if ("OPEN".equals(request.getStatus())) return !request.getRequester().getId().equals(volunteerId) && isOldEnough(request) && !isPast(request);
        boolean assignedToThisVolunteer = request.getVolunteer() != null && request.getVolunteer().getId().equals(volunteerId);
        return assignedToThisVolunteer && ("ACCEPTED".equals(request.getStatus()) || "COMPLETED".equals(request.getStatus()));
    }

    private List<HelpRequestEntity> findReplacementHelpRequests(Long volunteerId, double latitude, double longitude, Set<Long> excludedRequestIds, Set<LocalDateTime> usedStarts, int count) {
        Set<Long> excluded = new HashSet<>(excludedRequestIds);
        excluded.addAll(activePersonalTargetIds(volunteerId, "VOLUNTEER", "HELP_REQUEST"));
        Set<LocalDateTime> starts = new HashSet<>(usedStarts);
        List<HelpRequestEntity> result = new ArrayList<>();
        for (HelpRequestEntity request : helpRequests.findByStatusOrderByDateAscTimeAscCreatedAtAsc("OPEN")) {
            if (request.getId() == null || excluded.contains(request.getId())) continue;
            if (request.getRequester().getId().equals(volunteerId)) continue;
            if (request.getStartLatitude() == null || request.getStartLongitude() == null) continue;
            if (!isOldEnough(request) || isPast(request)) continue;
            if (distanceKm(latitude, longitude, request.getStartLatitude(), request.getStartLongitude()) > RADIUS_KM) continue;
            LocalDateTime start = startOf(request);
            if (!starts.add(start)) continue;
            result.add(request);
            excluded.add(request.getId());
            if (result.size() == count) break;
        }
        return result;
    }

    private Set<Long> activePersonalTargetIds(Long userId, String activityType, String targetType) {
        List<TaskEntity> active = tasks.findByActivityTypeAndStatusAndAssignedUserIdOrderByCreatedAtDesc(activityType, "ACTIVE", userId);
        if (active.isEmpty()) return Set.of();
        return targets.findByTaskIdInOrderBySortOrderAscIdAsc(active.stream().map(TaskEntity::getId).toList()).stream()
                .filter(target -> targetType.equals(target.getTargetType()))
                .filter(target -> target.getStatus() == null || !"UNAVAILABLE".equals(target.getStatus()))
                .map(TaskTargetEntity::getTargetId)
                .collect(Collectors.toSet());
    }

    private TaskTargetEntity addTarget(TaskEntity task, String targetType, Long targetId, String title, Double latitude, Double longitude, int order) {
        TaskTargetEntity target = new TaskTargetEntity();
        target.setTaskId(task.getId());
        target.setTargetType(targetType);
        target.setTargetId(targetId);
        target.setTitle(title);
        target.setLatitude(latitude);
        target.setLongitude(longitude);
        target.setSortOrder(order);
        target.setStatus("ACTIVE");
        return targets.save(target);
    }

    private boolean isOldEnough(HelpRequestEntity request) {
        return request.getCreatedAt() != null && request.getCreatedAt().plus(HELP_REQUEST_MIN_AGE).isBefore(Instant.now());
    }

    private boolean isPast(HelpRequestEntity request) {
        return LocalDateTime.of(request.getDate(), request.getTime()).isBefore(LocalDateTime.now());
    }

    private LocalDateTime startOf(HelpRequestEntity request) {
        return LocalDateTime.of(request.getDate(), request.getTime());
    }

    private String volunteerTaskTitle(int count) {
        return count == 1 ? "Помогите одному человеку с прогулкой рядом с вами" : "Помогите трем людям с прогулкой рядом с вами";
    }

    private String helpRequestTitle(HelpRequestEntity request) {
        return request.getFromAddress() + " → " + request.getToAddress() + ", " + request.getDate() + " " + request.getTime();
    }

    @Transactional
    public void completeTarget(String phoneFromAuth, String taskId, String targetId) {
        UserEntity user = findCurrent(phoneFromAuth);
        Long taskIdLong = Long.valueOf(taskId);
        Long targetIdLong = Long.valueOf(targetId);
        TaskEntity task = tasks.findById(taskIdLong).orElseThrow(() -> bad("TASK_NOT_FOUND", "Task not found"));
        TaskTargetEntity target = targets.findById(targetIdLong).orElseThrow(() -> bad("TARGET_NOT_FOUND", "Target not found"));
        if (!target.getTaskId().equals(taskIdLong)) throw bad("TARGET_NOT_BELONG_TO_TASK", "Target does not belong to task");
        if (task.getAssignedUserId() != null && !task.getAssignedUserId().equals(user.getId())) throw bad("TASK_NOT_FOUND", "Task not found");
        if (taskCompletions.existsByUserIdAndTaskId(user.getId(), taskIdLong)) throw bad("TASK_ALREADY_COMPLETED", "Task already completed");
        if (targetCompletions.existsByUserIdAndTargetId(user.getId(), targetIdLong)) throw bad("TARGET_ALREADY_COMPLETED", "Target already completed");
        UserTaskTargetCompletionEntity completion = new UserTaskTargetCompletionEntity();
        completion.setUserId(user.getId());
        completion.setTaskId(taskIdLong);
        completion.setTargetId(targetIdLong);
        completion.setSourceType("MANUAL");
        completion.setSourceId(System.currentTimeMillis());
        targetCompletions.save(completion);
        if (targetCompletions.countByUserIdAndTaskId(user.getId(), taskIdLong) >= task.getTargetCount()) {
            completeTask(user, task, "MANUAL", System.currentTimeMillis());
        }
    }

    private String address(ObstacleFeatureEntity f) {
        String place = trim(f.getPlaceName());
        String base = String.join(", ", java.util.stream.Stream.of(f.getCity(), f.getStreet(), f.getHouse()).filter(Objects::nonNull).filter(s -> !s.isBlank()).toList());
        return place == null ? base : place + ", " + base;
    }

    private boolean isNear(Double centerLat, Double centerLon, Double lat, Double lon) {
        if (lat == null || lon == null || centerLat == null || centerLon == null) return true;
        return distanceKm(lat, lon, centerLat, centerLon) <= RADIUS_KM;
    }

    private double distanceKm(double lat1, double lon1, double lat2, double lon2) {
        double r = 6371.0;
        double dLat = Math.toRadians(lat2 - lat1);
        double dLon = Math.toRadians(lon2 - lon1);
        double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                * Math.sin(dLon / 2) * Math.sin(dLon / 2);
        return r * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    }

    private int defaultPoints(String type, int count) {
        if ("VOLUNTEER".equals(type)) return count == 1 ? 50 : 120;
        return count == 3 ? 30 : count == 5 ? 50 : 100;
    }

    private boolean isAllowedTargetCount(String type, int count) {
        if ("VOLUNTEER".equals(type)) return count == 1 || count == 3;
        return count == 3 || count == 5 || count == 10;
    }

    private String requireTargetType(String raw, String activityType) {
        String type = trim(raw);
        if ("REVIEW".equals(activityType) && "OBSTACLE_FEATURE".equals(type)) return type;
        if ("VOLUNTEER".equals(activityType) && "HELP_REQUEST".equals(type)) return type;
        throw bad("TASK_TARGET_TYPE_INVALID", "Task target type is invalid");
    }

    private String normalizeActivity(String raw) {
        String v = trim(raw);
        if (v == null) return null;
        v = v.toUpperCase(Locale.ROOT);
        if (v.equals("REVIEWS")) v = "REVIEW";
        if (v.equals("VOLUNTEERING")) v = "VOLUNTEER";
        return (v.equals("REVIEW") || v.equals("VOLUNTEER")) ? v : null;
    }

    private UserEntity findCurrent(String phoneFromAuth) {
        String phoneNorm = Crypto.normPhone(phoneFromAuth);
        if (phoneNorm.isEmpty()) throw new ApiException(HttpStatus.UNAUTHORIZED, "USER_PHONE_NOT_FOUND", "User with given phone not found");
        return users.findByPhoneHash(Crypto.sha256Hex(phoneNorm))
                .orElseThrow(() -> new ApiException(HttpStatus.UNAUTHORIZED, "USER_PHONE_NOT_FOUND", "User with given phone not found"));
    }

    private ApiException bad(String code, String msg) { return new ApiException(HttpStatus.BAD_REQUEST, code, msg); }
    private static String trim(String s) { return s == null || s.isBlank() ? null : s.trim(); }
    private static int safe(Integer v) { return v == null ? 0 : Math.max(0, v); }
}