package goodroad.tasks;

import goodroad.api.ApiErrors.ApiException;
import goodroad.obstacle.repository.*;
import goodroad.points.PointLedgerService;
import goodroad.security.Crypto;
import goodroad.tasks.repository.*;
import goodroad.users.repository.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class TaskService {
    private static final double RADIUS_KM = 5.0;

    private final UserRepo users;
    private final TaskRepo tasks;
    private final TaskTargetRepo targets;
    private final UserTaskTargetCompletionRepo targetCompletions;
    private final UserTaskCompletionRepo taskCompletions;
    private final ObstacleFeatureRepo features;
    private final PointLedgerService ledger;

    public TaskService(UserRepo users, TaskRepo tasks, TaskTargetRepo targets,
                       UserTaskTargetCompletionRepo targetCompletions, UserTaskCompletionRepo taskCompletions,
                       ObstacleFeatureRepo features, PointLedgerService ledger) {
        this.users = users;
        this.tasks = tasks;
        this.targets = targets;
        this.targetCompletions = targetCompletions;
        this.taskCompletions = taskCompletions;
        this.features = features;
        this.ledger = ledger;
    }

    public record TargetView(String id, String targetType, String targetId, String title, Double latitude, Double longitude, boolean done) {}
    public record TaskView(String id, String activityType, String title, int points, int targetCount, int completedCount, boolean autoGenerated, List<TargetView> targets) {}
    public record CompletedTaskView(String id, String taskId, String taskTitle, int pointsAwarded, java.time.Instant createdAt) {}
    public record TaskCreateReq(String activityType, String title, int targetCount, Integer points, Double latitude, Double longitude, List<TaskTargetCreateReq> targets) {}
    public record TaskTargetCreateReq(String targetType, Long targetId, String title, Double latitude, Double longitude) {}

    @Transactional
    public List<TaskView> feed(String phoneFromAuth, String activityType, Double latitude, Double longitude) {
        UserEntity user = findCurrent(phoneFromAuth);
        if (latitude != null && longitude != null) generateReviewTasks(latitude, longitude);
        List<TaskEntity> raw = normalizeActivity(activityType) == null
                ? tasks.findByStatusOrderByCreatedAtDesc("ACTIVE")
                : tasks.findByActivityTypeAndStatusOrderByCreatedAtDesc(normalizeActivity(activityType), "ACTIVE");
        raw = raw.stream()
                .filter(task -> !taskCompletions.existsByUserIdAndTaskId(user.getId(), task.getId()))
                .filter(task -> isNear(task.getCenterLatitude(), task.getCenterLongitude(), latitude, longitude))
                .toList();
        return buildViews(user, raw);
    }

    @Transactional(readOnly = true)
    public List<CompletedTaskView> completed(String phoneFromAuth) {
        UserEntity user = findCurrent(phoneFromAuth);
        return taskCompletions.findByUserIdOrderByCreatedAtDesc(user.getId()).stream()
                .map(c -> {
                    TaskEntity task = tasks.findById(c.getTaskId()).orElse(null);
                    String taskTitle = task != null ? task.getTitle() : "Задание";
                    return new CompletedTaskView(
                            c.getId() == null ? null : c.getId().toString(),
                            c.getTaskId().toString(),
                            taskTitle,
                            c.getPointsAwarded(),
                            c.getCreatedAt()
                    );
                })
                .toList();
    }

    @Transactional
    public TaskView createTask(TaskCreateReq req) {
        if (req == null) throw bad("TASK_EMPTY", "Task is empty");
        String type = normalizeActivity(req.activityType());
        if (type == null) throw bad("TASK_ACTIVITY_INVALID", "Task activity type is invalid");
        int targetCount = req.targetCount();
        if (targetCount != 3 && targetCount != 5 && targetCount != 10) throw bad("TASK_TARGET_COUNT_INVALID", "Task target count is invalid");
        int points = req.points() == null ? defaultPoints(type, targetCount) : req.points();
        if (points <= 0) throw bad("TASK_POINTS_INVALID", "Task points are invalid");
        String title = trim(req.title());
        if (title == null) throw bad("TASK_TITLE_EMPTY", "Task title is empty");
        if (req.targets() == null || req.targets().size() < targetCount) throw bad("TASK_TARGETS_NOT_ENOUGH", "Task targets are not enough");
        TaskEntity task = new TaskEntity();
        task.setActivityType(type);
        task.setTitle(title);
        task.setTargetCount(targetCount);
        task.setPoints(points);
        task.setCenterLatitude(req.latitude());
        task.setCenterLongitude(req.longitude());
        tasks.save(task);
        int order = 0;
        for (TaskTargetCreateReq targetReq : req.targets().stream().limit(targetCount).toList()) {
            TaskTargetEntity target = new TaskTargetEntity();
            target.setTaskId(task.getId());
            target.setTargetType(requireTargetType(targetReq.targetType(), type));
            target.setTargetId(Objects.requireNonNull(targetReq.targetId(), "targetId"));
            target.setTitle(Optional.ofNullable(trim(targetReq.title())).orElse("Цель задания #" + targetReq.targetId()));
            target.setLatitude(targetReq.latitude());
            target.setLongitude(targetReq.longitude());
            target.setSortOrder(order++);
            targets.save(target);
        }
        return buildViews(null, List.of(task)).get(0);
    }

    @Transactional
    public void registerApprovedReview(Long userId, Long featureId, Long reviewId) {
        registerTargetCompletion(userId, "OBSTACLE_FEATURE", featureId, "REVIEW", reviewId);
    }

    @Transactional
    public void registerCompletedHelp(Long volunteerId, Long helpRequestId) {
        registerTargetCompletion(volunteerId, "HELP_REQUEST", helpRequestId, "HELP_REQUEST", helpRequestId);
    }

    private void registerTargetCompletion(Long userId, String targetType, Long targetObjectId, String sourceType, Long sourceId) {
        if (userId == null || targetObjectId == null) return;
        UserEntity user = users.findById(userId).orElse(null);
        if (user == null) return;
        for (TaskTargetEntity target : targets.findByTargetTypeAndTargetId(targetType, targetObjectId)) {
            if (taskCompletions.existsByUserIdAndTaskId(userId, target.getTaskId()) || targetCompletions.existsByUserIdAndTargetId(userId, target.getId())) continue;
            UserTaskTargetCompletionEntity done = new UserTaskTargetCompletionEntity();
            done.setUserId(userId);
            done.setTaskId(target.getTaskId());
            done.setTargetId(target.getId());
            done.setSourceType(sourceType);
            done.setSourceId(sourceId);
            targetCompletions.save(done);
            TaskEntity task = tasks.findById(target.getTaskId()).orElse(null);
            if (task != null && targetCompletions.countByUserIdAndTaskId(userId, task.getId()) >= task.getTargetCount()) {
                completeTask(user, task, sourceType, sourceId);
            }
        }
    }

    private void completeTask(UserEntity user, TaskEntity task, String sourceType, Long sourceId) {
        if (taskCompletions.existsByUserIdAndTaskId(user.getId(), task.getId())) return;
        UserTaskCompletionEntity completion = new UserTaskCompletionEntity();
        completion.setUserId(user.getId());
        completion.setTaskId(task.getId());
        completion.setPointsAwarded(task.getPoints());
        taskCompletions.save(completion);
        user.setCompletedTasksCount(safe(user.getCompletedTasksCount()) + 1);
        ledger.earn(user, task.getPoints(), "TASK_COMPLETED", task.getTitle(), task.getId(), sourceType, sourceId);
    }

    private List<TaskView> buildViews(UserEntity user, List<TaskEntity> rawTasks) {
        if (rawTasks.isEmpty()) return List.of();
        List<Long> taskIds = rawTasks.stream().map(TaskEntity::getId).toList();
        Map<Long, List<TaskTargetEntity>> byTask = targets.findByTaskIdInOrderBySortOrderAscIdAsc(taskIds).stream()
                .collect(Collectors.groupingBy(TaskTargetEntity::getTaskId, LinkedHashMap::new, Collectors.toList()));
        Set<Long> doneTargetIds = user == null ? Set.of() : targetCompletions.findByUserIdAndTaskIdIn(user.getId(), taskIds).stream()
                .map(UserTaskTargetCompletionEntity::getTargetId).collect(Collectors.toSet());
        return rawTasks.stream().map(task -> {
            List<TargetView> targetViews = byTask.getOrDefault(task.getId(), List.of()).stream()
                    .map(target -> new TargetView(target.getId().toString(), target.getTargetType(), target.getTargetId().toString(), target.getTitle(), target.getLatitude(), target.getLongitude(), doneTargetIds.contains(target.getId())))
                    .toList();
            int completedCount = (int) targetViews.stream().filter(TargetView::done).count();
            return new TaskView(task.getId().toString(), task.getActivityType(), task.getTitle(), task.getPoints(), task.getTargetCount(), completedCount, task.isAutoGenerated(), targetViews);
        }).toList();
    }

    private void generateReviewTasks(double latitude, double longitude) {
        for (int count : List.of(3, 5, 10)) {
            String title = "Оцените " + count + " мало проверенных точек рядом с вами";
            if (tasks.existsByTitleAndStatus(title, "ACTIVE")) continue;
            List<ObstacleFeatureEntity> picked = features.findLowReviewedByBbox(latitude - 0.06, latitude + 0.06, longitude - 0.1, longitude + 0.1, 1).stream()
                    .filter(f -> distanceKm(latitude, longitude, f.getLat(), f.getLon()) <= RADIUS_KM)
                    .limit(count)
                    .toList();
            if (picked.size() < count) continue;
            TaskEntity task = new TaskEntity();
            task.setActivityType("REVIEW");
            task.setTitle(title);
            task.setTargetCount(count);
            task.setPoints(defaultPoints("REVIEW", count));
            task.setAutoGenerated(true);
            task.setCenterLatitude(latitude);
            task.setCenterLongitude(longitude);
            tasks.save(task);
            int order = 0;
            for (ObstacleFeatureEntity feature : picked) {
                TaskTargetEntity target = new TaskTargetEntity();
                target.setTaskId(task.getId());
                target.setTargetType("OBSTACLE_FEATURE");
                target.setTargetId(feature.getId());
                target.setTitle(address(feature));
                target.setLatitude(feature.getLat());
                target.setLongitude(feature.getLon());
                target.setSortOrder(order++);
                targets.save(target);
            }
        }
    }

    @Transactional
    public void completeTarget(String phoneFromAuth, String taskId, String targetId) {
        UserEntity user = findCurrent(phoneFromAuth);
        Long taskIdLong = Long.valueOf(taskId);
        Long targetIdLong = Long.valueOf(targetId);

        TaskEntity task = tasks.findById(taskIdLong)
                .orElseThrow(() -> bad("TASK_NOT_FOUND", "Task not found"));

        TaskTargetEntity target = targets.findById(targetIdLong)
                .orElseThrow(() -> bad("TARGET_NOT_FOUND", "Target not found"));

        if (!target.getTaskId().equals(taskIdLong)) {
            throw bad("TARGET_NOT_BELONG_TO_TASK", "Target does not belong to task");
        }

        if (taskCompletions.existsByUserIdAndTaskId(user.getId(), taskIdLong)) {
            throw bad("TASK_ALREADY_COMPLETED", "Task already completed");
        }

        if (targetCompletions.existsByUserIdAndTargetId(user.getId(), targetIdLong)) {
            throw bad("TARGET_ALREADY_COMPLETED", "Target already completed");
        }

        UserTaskTargetCompletionEntity completion = new UserTaskTargetCompletionEntity();
        completion.setUserId(user.getId());
        completion.setTaskId(taskIdLong);
        completion.setTargetId(targetIdLong);
        completion.setSourceType("MANUAL");
        completion.setSourceId(System.currentTimeMillis()); // или можно передавать какой-то ID
        targetCompletions.save(completion);

        long completedCount = targetCompletions.countByUserIdAndTaskId(user.getId(), taskIdLong);
        if (completedCount >= task.getTargetCount()) {
            completeTask(user, task, "MANUAL", System.currentTimeMillis());
        }
    }

    private String address(ObstacleFeatureEntity f) {
        String place = trim(f.getPlaceName());
        String base = String.join(", ", java.util.stream.Stream.of(f.getCity(), f.getStreet(), f.getHouse()).filter(Objects::nonNull).filter(s -> !s.isBlank()).toList());
        return place == null ? base : place + ", " + base;
    }

    private boolean isNear(Double centerLat, Double centerLon, Double lat, Double lon) {
        if (lat == null || lon == null || centerLat == null || centerLon == null) return true;
        return distanceKm(lat, lon, centerLat, centerLon) <= RADIUS_KM;
    }

    private double distanceKm(double lat1, double lon1, double lat2, double lon2) {
        double r = 6371.0;
        double dLat = Math.toRadians(lat2 - lat1);
        double dLon = Math.toRadians(lon2 - lon1);
        double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                * Math.sin(dLon / 2) * Math.sin(dLon / 2);
        return r * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    }

    private int defaultPoints(String type, int count) {
        if ("VOLUNTEER".equals(type)) return count == 3 ? 130 : count == 5 ? 150 : 200;
        return count == 3 ? 30 : count == 5 ? 50 : 100;
    }

    private String requireTargetType(String raw, String activityType) {
        String type = trim(raw);
        if ("REVIEW".equals(activityType) && "OBSTACLE_FEATURE".equals(type)) return type;
        if ("VOLUNTEER".equals(activityType) && "HELP_REQUEST".equals(type)) return type;
        throw bad("TASK_TARGET_TYPE_INVALID", "Task target type is invalid");
    }

    private String normalizeActivity(String raw) {
        String v = trim(raw);
        if (v == null) return null;
        v = v.toUpperCase(Locale.ROOT);
        if (v.equals("REVIEWS")) v = "REVIEW";
        if (v.equals("VOLUNTEERING")) v = "VOLUNTEER";
        return (v.equals("REVIEW") || v.equals("VOLUNTEER")) ? v : null;
    }

    private UserEntity findCurrent(String phoneFromAuth) {
        String phoneNorm = Crypto.normPhone(phoneFromAuth);
        if (phoneNorm.isEmpty()) throw new ApiException(HttpStatus.UNAUTHORIZED, "USER_PHONE_NOT_FOUND", "User with given phone not found");
        return users.findByPhoneHash(Crypto.sha256Hex(phoneNorm))
                .orElseThrow(() -> new ApiException(HttpStatus.UNAUTHORIZED, "USER_PHONE_NOT_FOUND", "User with given phone not found"));
    }

    private ApiException bad(String code, String msg) { return new ApiException(HttpStatus.BAD_REQUEST, code, msg); }
    private static String trim(String s) { return s == null || s.isBlank() ? null : s.trim(); }
    private static int safe(Integer v) { return v == null ? 0 : Math.max(0, v); }
}