services:
  db:
    image: postgis/postgis:16-3.4
    container_name: goodroad_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - goodroad_db:/var/lib/postgresql/data

volumes:
  goodroad_db: