spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

yandex:
  storage:
    endpoint: https://storage.yandexcloud.net
    bucket: ${YC_BUCKET}
    region: ru-central1
    access-key: ${YC_ACCESS_KEY}
    secret-key: ${YC_SECRET_KEY}

app:
  admin:
    phone: ${ADMIN_PHONE}
    pass: ${ADMIN_PASS}

logging:
  level:
    root: INFO
    goodroad: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n"

