alter table users drop constraint if exists users_role_check;
alter table users add constraint users_role_check
    check (role in ('USER', 'VOLUNTEER', 'MODERATOR', 'MODERATOR_ADMIN'));

create table if not exists volunteer_application (
    id bigint generated by default as identity primary key,
    applicant_id bigint not null references users(id) on delete cascade,
    dobro_url varchar(512) not null,
    phone varchar(32) not null,
    social_nickname varchar(120),
    status varchar(16) not null check (status in ('PENDING', 'APPROVED', 'REJECTED')),
    moderator_comment varchar(1000),
    moderator_id bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    moderated_at timestamptz
);

create index if not exists ix_volunteer_application_applicant_created
    on volunteer_application(applicant_id, created_at desc);
create index if not exists ix_volunteer_application_status_created
    on volunteer_application(status, created_at asc);

create table if not exists volunteer_application_photo (
    id bigint generated by default as identity primary key,
    application_id bigint not null references volunteer_application(id) on delete cascade,
    url varchar(512) not null,
    created_at timestamptz not null default now()
);

create index if not exists ix_volunteer_application_photo_application
    on volunteer_application_photo(application_id);

create table if not exists volunteer_user_state (
    user_id bigint primary key references users(id) on delete cascade,
    volunteer_warnings integer not null default 0 check (volunteer_warnings between 0 and 3),
    requester_warnings integer not null default 0 check (requester_warnings between 0 and 3),
    volunteer_banned_until timestamptz
);

create table if not exists help_request (
    id bigint generated by default as identity primary key,
    requester_id bigint not null references users(id) on delete cascade,
    volunteer_id bigint references users(id) on delete set null,
    from_address varchar(500) not null,
    to_address varchar(500) not null,
    walk_date date not null,
    walk_time time not null,
    phone varchar(32) not null,
    social_nickname varchar(120),
    comment varchar(2000) not null,
    status varchar(16) not null check (status in ('OPEN', 'ACCEPTED', 'CANCELLED', 'COMPLETED')),
    created_at timestamptz not null default now(),
    accepted_at timestamptz,
    cancelled_at timestamptz,
    requester_started_at timestamptz,
    volunteer_started_at timestamptz,
    started_at timestamptz,
    requester_finished_at timestamptz,
    volunteer_finished_at timestamptz,
    completed_at timestamptz,
    requester_latitude double precision check (requester_latitude is null or requester_latitude between -90 and 90),
    requester_longitude double precision check (requester_longitude is null or requester_longitude between -180 and 180),
    volunteer_latitude double precision check (volunteer_latitude is null or volunteer_latitude between -90 and 90),
    volunteer_longitude double precision check (volunteer_longitude is null or volunteer_longitude between -180 and 180),
    planned_route_points text
);

create index if not exists ix_help_request_requester_date
    on help_request(requester_id, walk_date desc, walk_time desc, created_at desc);
create index if not exists ix_help_request_volunteer_date
    on help_request(volunteer_id, walk_date desc, walk_time desc, created_at desc);
create index if not exists ix_help_request_status_date
    on help_request(status, walk_date asc, walk_time asc, created_at asc);

create table if not exists volunteer_complaint (
    id bigint generated by default as identity primary key,
    request_id bigint not null references help_request(id) on delete cascade,
    author_id bigint not null references users(id) on delete cascade,
    target_id bigint not null references users(id) on delete cascade,
    text varchar(2000) not null,
    status varchar(16) not null check (status in ('PENDING', 'RESOLVED')),
    guilty_user_id bigint references users(id) on delete set null,
    moderator_id bigint references users(id) on delete set null,
    moderator_comment varchar(1000),
    created_at timestamptz not null default now(),
    resolved_at timestamptz
);

create index if not exists ix_volunteer_complaint_status_created
    on volunteer_complaint(status, created_at asc);

create table if not exists volunteer_sos_notification (
    id bigint generated by default as identity primary key,
    request_id bigint not null references help_request(id) on delete cascade,
    sender_id bigint not null references users(id) on delete cascade,
    reason varchar(64) not null,
    comment varchar(1000),
    status varchar(16) not null default 'OPEN'
        check (status in ('OPEN', 'CONFIRMED', 'FALSE_ALARM', 'RESOLVED')),
    moderator_id bigint references users(id) on delete set null,
    moderator_comment varchar(1000),
    created_at timestamptz not null default now(),
    resolved_at timestamptz
);

create index if not exists ix_volunteer_sos_created
    on volunteer_sos_notification(created_at desc);
create index if not exists ix_volunteer_sos_status_created
    on volunteer_sos_notification(status, created_at desc);
