alter table users drop constraint if exists users_role_check;
alter table users add constraint users_role_check
    check (role in ('USER', 'VOLUNTEER', 'MODERATOR', 'MODERATOR_ADMIN'));

create table if not exists volunteer_application (
                                                     id bigint generated by default as identity primary key,
                                                     applicant_id bigint not null references users(id) on delete cascade,
    dobro_url varchar(512) not null,
    phone varchar(32) not null,
    social_nickname varchar(120),
    status varchar(16) not null check (status in ('PENDING', 'APPROVED', 'REJECTED')),
    moderator_comment varchar(1000),
    moderator_id bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    moderated_at timestamptz
    );

create index if not exists ix_volunteer_application_applicant_created
    on volunteer_application(applicant_id, created_at desc);
create index if not exists ix_volunteer_application_status_created
    on volunteer_application(status, created_at asc);

create table if not exists volunteer_application_photo (
                                                           id bigint generated by default as identity primary key,
                                                           application_id bigint not null references volunteer_application(id) on delete cascade,
    url varchar(512) not null,
    created_at timestamptz not null default now()
    );

create index if not exists ix_volunteer_application_photo_application
    on volunteer_application_photo(application_id);

create table if not exists help_request (
                                            id bigint generated by default as identity primary key,
                                            requester_id bigint not null references users(id) on delete cascade,
    volunteer_id bigint references users(id) on delete set null,
    from_address varchar(500) not null,
    to_address varchar(500) not null,
    walk_date date not null,
    walk_time time not null,
    phone varchar(32) not null,
    social_nickname varchar(120),
    comment varchar(2000) not null,
    status varchar(16) not null check (status in ('OPEN', 'ACCEPTED', 'CANCELLED', 'COMPLETED')),
    created_at timestamptz not null default now(),
    accepted_at timestamptz,
    cancelled_at timestamptz,
    requester_finished_at timestamptz,
    volunteer_finished_at timestamptz,
    completed_at timestamptz,
    planned_route_points text
    );

create index if not exists ix_help_request_requester_date
    on help_request(requester_id, walk_date desc, walk_time desc, created_at desc);
create index if not exists ix_help_request_volunteer_date
    on help_request(volunteer_id, walk_date desc, walk_time desc, created_at desc);
create index if not exists ix_help_request_status_date
    on help_request(status, walk_date asc, walk_time asc, created_at asc);
