alter table users add column if not exists lifetime_points integer not null default 0 check (lifetime_points >= 0);
alter table users add column if not exists completed_tasks_count integer not null default 0 check (completed_tasks_count >= 0);

update users set lifetime_points = greatest(lifetime_points, total_points) where lifetime_points < total_points;

create table if not exists point_transaction (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    direction varchar(8) not null check (direction in ('EARN', 'SPEND')),
    amount integer not null check (amount > 0),
    reason varchar(120) not null,
    details varchar(1000),
    task_id bigint,
    reward_offer_id bigint,
    source_type varchar(64),
    source_id bigint,
    created_at timestamptz not null default now()
);

create index if not exists ix_point_transaction_user_created on point_transaction(user_id, created_at desc);
create index if not exists ix_point_transaction_direction on point_transaction(direction);

create table if not exists reward_offer (
    id bigint generated by default as identity primary key,
    partner_name varchar(180) not null,
    title varchar(240) not null,
    description varchar(1000),
    price integer not null check (price > 0),
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists ix_reward_offer_active_price on reward_offer(active, price);
create index if not exists ix_reward_offer_partner on reward_offer(partner_name);
create unique index if not exists uq_reward_offer_partner_title on reward_offer(partner_name, title);

create table if not exists user_reward_purchase (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    reward_offer_id bigint not null references reward_offer(id) on delete restrict,
    price integer not null check (price > 0),
    created_at timestamptz not null default now()
);

create index if not exists ix_user_reward_purchase_user_created on user_reward_purchase(user_id, created_at desc);

create table if not exists task (
    id bigint generated by default as identity primary key,
    activity_type varchar(16) not null check (activity_type in ('REVIEW', 'VOLUNTEER')),
    title varchar(500) not null,
    points integer not null check (points > 0),
    target_count integer not null check (target_count in (3, 5, 10)),
    status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'ARCHIVED')),
    auto_generated boolean not null default false,
    center_latitude double precision,
    center_longitude double precision,
    created_at timestamptz not null default now(),
    constraint task_center_valid check (
        (center_latitude is null and center_longitude is null) or
        (center_latitude between -90 and 90 and center_longitude between -180 and 180)
    )
);

create index if not exists ix_task_activity_status on task(activity_type, status);
create index if not exists ix_task_center on task(center_latitude, center_longitude);
create unique index if not exists uq_task_title_active on task(title) where status = 'ACTIVE';

create table if not exists task_target (
    id bigint generated by default as identity primary key,
    task_id bigint not null references task(id) on delete cascade,
    target_type varchar(32) not null check (target_type in ('OBSTACLE_FEATURE', 'HELP_REQUEST')),
    target_id bigint not null,
    title varchar(500) not null,
    latitude double precision,
    longitude double precision,
    sort_order integer not null default 0,
    constraint task_target_unique unique (task_id, target_type, target_id)
);

create index if not exists ix_task_target_task on task_target(task_id, sort_order);
create index if not exists ix_task_target_lookup on task_target(target_type, target_id);

create table if not exists user_task_target_completion (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    task_id bigint not null references task(id) on delete cascade,
    target_id bigint not null references task_target(id) on delete cascade,
    source_type varchar(64) not null,
    source_id bigint not null,
    created_at timestamptz not null default now(),
    constraint user_task_target_once unique (user_id, target_id)
);

create index if not exists ix_user_task_target_completion_task_user on user_task_target_completion(task_id, user_id);

create table if not exists user_task_completion (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    task_id bigint not null references task(id) on delete cascade,
    points_awarded integer not null check (points_awarded > 0),
    created_at timestamptz not null default now(),
    constraint user_task_once unique (user_id, task_id)
);

create index if not exists ix_user_task_completion_user_created on user_task_completion(user_id, created_at desc);
