-- Explicit, throttled task generation state.
create table if not exists task_generation_state (
    user_id bigint primary key references users(id) on delete cascade,
    latitude double precision not null check (latitude between -90 and 90),
    longitude double precision not null check (longitude between -180 and 180),
    generated_at timestamptz not null
);

-- Remove duplicate active personal task variants before enforcing idempotency.
with ranked as (
    select id,
           row_number() over (
               partition by assigned_user_id, activity_type, target_count
               order by created_at desc, id desc
           ) as position
    from task
    where status = 'ACTIVE' and assigned_user_id is not null
)
update task
set status = 'ARCHIVED'
where id in (select id from ranked where position > 1);

create unique index if not exists uq_task_active_personal_variant
    on task(assigned_user_id, activity_type, target_count)
    where status = 'ACTIVE' and assigned_user_id is not null;

alter table reward_offer
    add column if not exists reward_type varchar(32) not null default 'PROMOCODE';
alter table reward_offer
    add column if not exists validity_days integer;

alter table reward_offer drop constraint if exists reward_offer_type_check;
alter table reward_offer add constraint reward_offer_type_check
    check (reward_type in ('COUPON', 'PROMOCODE', 'PARTNER_REWARD'));
alter table reward_offer drop constraint if exists reward_offer_validity_days_check;
alter table reward_offer add constraint reward_offer_validity_days_check
    check (validity_days is null or validity_days between 1 and 3650);

create table if not exists reward_inventory_item (
    id bigint generated by default as identity primary key,
    reward_offer_id bigint not null references reward_offer(id) on delete cascade,
    code varchar(512) not null,
    status varchar(16) not null default 'AVAILABLE'
        check (status in ('AVAILABLE', 'ASSIGNED', 'CANCELLED')),
    valid_until timestamptz,
    created_at timestamptz not null default now(),
    assigned_at timestamptz,
    constraint uq_reward_inventory_code unique (reward_offer_id, code)
);

create index if not exists ix_reward_inventory_available
    on reward_inventory_item(reward_offer_id, status, valid_until, id);

alter table user_reward_purchase add column if not exists inventory_item_id bigint;
alter table user_reward_purchase add column if not exists status varchar(16) not null default 'ACTIVE';
alter table user_reward_purchase add column if not exists expires_at timestamptz;
alter table user_reward_purchase add column if not exists redeemed_at timestamptz;

-- Preserve historical purchases by creating one assigned inventory item per old row.
insert into reward_inventory_item(reward_offer_id, code, status, created_at, assigned_at)
select purchase.reward_offer_id,
       'LEGACY-' || purchase.id,
       'ASSIGNED',
       purchase.created_at,
       purchase.created_at
from user_reward_purchase purchase
where purchase.inventory_item_id is null
on conflict (reward_offer_id, code) do nothing;

update user_reward_purchase purchase
set inventory_item_id = item.id
from reward_inventory_item item
where purchase.inventory_item_id is null
  and item.reward_offer_id = purchase.reward_offer_id
  and item.code = 'LEGACY-' || purchase.id;

alter table user_reward_purchase
    alter column inventory_item_id set not null;
alter table user_reward_purchase drop constraint if exists fk_user_reward_inventory_item;
alter table user_reward_purchase add constraint fk_user_reward_inventory_item
    foreign key (inventory_item_id) references reward_inventory_item(id) on delete restrict;
alter table user_reward_purchase drop constraint if exists user_reward_purchase_status_check;
alter table user_reward_purchase add constraint user_reward_purchase_status_check
    check (status in ('ACTIVE', 'REDEEMED', 'EXPIRED', 'CANCELLED'));
create unique index if not exists uq_user_reward_inventory_item
    on user_reward_purchase(inventory_item_id);
create index if not exists ix_user_reward_purchase_user_status
    on user_reward_purchase(user_id, status, created_at desc);
