package goodroad.tasks.repository;

import jakarta.persistence.*;
import java.time.Instant;

@Entity
@Table(name = "task")
public class TaskEntity {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "activity_type", nullable = false, length = 16)
    private String activityType;
    @Column(name = "title", nullable = false, length = 500)
    private String title;
    @Column(name = "points", nullable = false)
    private Integer points;
    @Column(name = "target_count", nullable = false)
    private Integer targetCount;
    @Column(name = "status", nullable = false, length = 16)
    private String status = "ACTIVE";
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;
    @Column(name = "center_latitude")
    private Double centerLatitude;
    @Column(name = "center_longitude")
    private Double centerLongitude;
    @Column(name = "assigned_user_id")
    private Long assignedUserId;
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;
    @PrePersist private void prePersist(){ if(createdAt==null) createdAt=Instant.now(); if(status==null) status="ACTIVE"; }
    public Long getId(){return id;} public void setId(Long id){this.id=id;}
    public String getActivityType(){return activityType;} public void setActivityType(String activityType){this.activityType=activityType;}
    public String getTitle(){return title;} public void setTitle(String title){this.title=title;}
    public Integer getPoints(){return points;} public void setPoints(Integer points){this.points=points;}
    public Integer getTargetCount(){return targetCount;} public void setTargetCount(Integer targetCount){this.targetCount=targetCount;}
    public String getStatus(){return status;} public void setStatus(String status){this.status=status;}
    public boolean isAutoGenerated(){return autoGenerated;} public void setAutoGenerated(boolean autoGenerated){this.autoGenerated=autoGenerated;}
    public Double getCenterLatitude(){return centerLatitude;} public void setCenterLatitude(Double centerLatitude){this.centerLatitude=centerLatitude;}
    public Double getCenterLongitude(){return centerLongitude;} public void setCenterLongitude(Double centerLongitude){this.centerLongitude=centerLongitude;}
    public Long getAssignedUserId(){return assignedUserId;} public void setAssignedUserId(Long assignedUserId){this.assignedUserId=assignedUserId;}
    public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant createdAt){this.createdAt=createdAt;}
}
